/* WebRecordingBindingService.cpp
   Generated by gSOAP 2.8.15 from web.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "WebRecordingBindingService.h"

RecordingBindingService::RecordingBindingService()
{	this->soap = soap_new();
	this->own = true;
	RecordingBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

RecordingBindingService::RecordingBindingService(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	RecordingBindingService_init(_soap->imode, _soap->omode);
}

RecordingBindingService::RecordingBindingService(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	RecordingBindingService_init(iomode, iomode);
}

RecordingBindingService::RecordingBindingService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	RecordingBindingService_init(imode, omode);
}

RecordingBindingService::~RecordingBindingService()
{	if (this->own)
		soap_free(this->soap);
}

void RecordingBindingService::RecordingBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"xmime", "http://www.w3.org/2005/05/xmlmime", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"dn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
	{"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
	{"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
	{"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"wsd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
};

void RecordingBindingService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void RecordingBindingService::reset()
{	destroy();
	soap_done(this->soap);
	soap_init(this->soap);
	RecordingBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
RecordingBindingService *RecordingBindingService::copy()
{	RecordingBindingService *dup = SOAP_NEW_COPY(RecordingBindingService);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

int RecordingBindingService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int RecordingBindingService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int RecordingBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int RecordingBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int RecordingBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int RecordingBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void RecordingBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void RecordingBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *RecordingBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void RecordingBindingService::soap_noheader()
{	this->soap->header = NULL;
}

void RecordingBindingService::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, char *wsa__MessageID, wsa__Relationship *wsa__RelatesTo, wsa__EndpointReferenceType *wsa__From, wsa__EndpointReferenceType *wsa__ReplyTo, wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, wsd__AppSequenceType *wsd__AppSequence)
{	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
	this->soap->header->wsa__MessageID = wsa__MessageID;
	this->soap->header->wsa__RelatesTo = wsa__RelatesTo;
	this->soap->header->wsa__From = wsa__From;
	this->soap->header->wsa__ReplyTo = wsa__ReplyTo;
	this->soap->header->wsa__FaultTo = wsa__FaultTo;
	this->soap->header->wsa__To = wsa__To;
	this->soap->header->wsa__Action = wsa__Action;
	this->soap->header->wsd__AppSequence = wsd__AppSequence;
}

const SOAP_ENV__Header *RecordingBindingService::soap_header()
{	return this->soap->header;
}

int RecordingBindingService::run(int port)
{	if (soap_valid_socket(this->soap->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->soap->error;
			soap_destroy(this->soap);
			soap_end(this->soap);
		}
	}
	else
		return this->soap->error;
	return SOAP_OK;
}

SOAP_SOCKET RecordingBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET RecordingBindingService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int RecordingBindingService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif

int RecordingBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->soap->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->soap->max_keep_alive > 0 && !--k)
			this->soap->keep_alive = 0;
#endif

		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if (dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___trc__GetServiceCapabilities(RecordingBindingService*);
static int serve___trc__CreateRecording(RecordingBindingService*);
static int serve___trc__DeleteRecording(RecordingBindingService*);
static int serve___trc__GetRecordings(RecordingBindingService*);
static int serve___trc__SetRecordingConfiguration(RecordingBindingService*);
static int serve___trc__GetRecordingConfiguration(RecordingBindingService*);
static int serve___trc__GetRecordingOptions(RecordingBindingService*);
static int serve___trc__CreateTrack(RecordingBindingService*);
static int serve___trc__DeleteTrack(RecordingBindingService*);
static int serve___trc__GetTrackConfiguration(RecordingBindingService*);
static int serve___trc__SetTrackConfiguration(RecordingBindingService*);
static int serve___trc__CreateRecordingJob(RecordingBindingService*);
static int serve___trc__DeleteRecordingJob(RecordingBindingService*);
static int serve___trc__GetRecordingJobs(RecordingBindingService*);
static int serve___trc__SetRecordingJobConfiguration(RecordingBindingService*);
static int serve___trc__GetRecordingJobConfiguration(RecordingBindingService*);
static int serve___trc__SetRecordingJobMode(RecordingBindingService*);
static int serve___trc__GetRecordingJobState(RecordingBindingService*);

int RecordingBindingService::dispatch()
{	RecordingBindingService_init(this->soap->imode, this->soap->omode);
	soap_peek_element(this->soap);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetServiceCapabilities")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetServiceCapabilities")))
		return serve___trc__GetServiceCapabilities(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:CreateRecording")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/CreateRecording")))
		return serve___trc__CreateRecording(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:DeleteRecording")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/DeleteRecording")))
		return serve___trc__DeleteRecording(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetRecordings")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetRecordings")))
		return serve___trc__GetRecordings(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:SetRecordingConfiguration")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/SetRecordingConfiguration")))
		return serve___trc__SetRecordingConfiguration(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetRecordingConfiguration")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetRecordingConfiguration")))
		return serve___trc__GetRecordingConfiguration(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetRecordingOptions")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetRecordingOptions")))
		return serve___trc__GetRecordingOptions(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:CreateTrack")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/CreateTrack")))
		return serve___trc__CreateTrack(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:DeleteTrack")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/DeleteTrack")))
		return serve___trc__DeleteTrack(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetTrackConfiguration")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetTrackConfiguration")))
		return serve___trc__GetTrackConfiguration(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:SetTrackConfiguration")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/SetTrackConfiguration")))
		return serve___trc__SetTrackConfiguration(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:CreateRecordingJob")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/CreateRecordingJob")))
		return serve___trc__CreateRecordingJob(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:DeleteRecordingJob")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/DeleteRecordingJob")))
		return serve___trc__DeleteRecordingJob(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetRecordingJobs")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobs")))
		return serve___trc__GetRecordingJobs(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:SetRecordingJobConfiguration")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobConfiguration")))
		return serve___trc__SetRecordingJobConfiguration(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetRecordingJobConfiguration")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobConfiguration")))
		return serve___trc__GetRecordingJobConfiguration(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:SetRecordingJobMode")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobMode")))
		return serve___trc__SetRecordingJobMode(this);
	if ((!this->soap->action && !soap_match_tag(this->soap, this->soap->tag, "trc:GetRecordingJobState")) || (this->soap->action && !strcmp(this->soap->action, "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobState")))
		return serve___trc__GetRecordingJobState(this);
	return this->soap->error = SOAP_NO_METHOD;
}

static int serve___trc__GetServiceCapabilities(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetServiceCapabilities soap_tmp___trc__GetServiceCapabilities;
	_trc__GetServiceCapabilitiesResponse trc__GetServiceCapabilitiesResponse;
	trc__GetServiceCapabilitiesResponse.soap_default(soap);
	soap_default___trc__GetServiceCapabilities(soap, &soap_tmp___trc__GetServiceCapabilities);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetServiceCapabilities(soap, &soap_tmp___trc__GetServiceCapabilities, "-trc:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetServiceCapabilities(soap_tmp___trc__GetServiceCapabilities.trc__GetServiceCapabilities, &trc__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetServiceCapabilitiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetServiceCapabilitiesResponse.soap_put(soap, "trc:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetServiceCapabilitiesResponse.soap_put(soap, "trc:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__CreateRecording(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__CreateRecording soap_tmp___trc__CreateRecording;
	_trc__CreateRecordingResponse trc__CreateRecordingResponse;
	trc__CreateRecordingResponse.soap_default(soap);
	soap_default___trc__CreateRecording(soap, &soap_tmp___trc__CreateRecording);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__CreateRecording(soap, &soap_tmp___trc__CreateRecording, "-trc:CreateRecording", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreateRecording(soap_tmp___trc__CreateRecording.trc__CreateRecording, &trc__CreateRecordingResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__CreateRecordingResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__CreateRecordingResponse.soap_put(soap, "trc:CreateRecordingResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__CreateRecordingResponse.soap_put(soap, "trc:CreateRecordingResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__DeleteRecording(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__DeleteRecording soap_tmp___trc__DeleteRecording;
	_trc__DeleteRecordingResponse trc__DeleteRecordingResponse;
	trc__DeleteRecordingResponse.soap_default(soap);
	soap_default___trc__DeleteRecording(soap, &soap_tmp___trc__DeleteRecording);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__DeleteRecording(soap, &soap_tmp___trc__DeleteRecording, "-trc:DeleteRecording", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->DeleteRecording(soap_tmp___trc__DeleteRecording.trc__DeleteRecording, &trc__DeleteRecordingResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__DeleteRecordingResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__DeleteRecordingResponse.soap_put(soap, "trc:DeleteRecordingResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__DeleteRecordingResponse.soap_put(soap, "trc:DeleteRecordingResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetRecordings(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetRecordings soap_tmp___trc__GetRecordings;
	_trc__GetRecordingsResponse trc__GetRecordingsResponse;
	trc__GetRecordingsResponse.soap_default(soap);
	soap_default___trc__GetRecordings(soap, &soap_tmp___trc__GetRecordings);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetRecordings(soap, &soap_tmp___trc__GetRecordings, "-trc:GetRecordings", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetRecordings(soap_tmp___trc__GetRecordings.trc__GetRecordings, &trc__GetRecordingsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetRecordingsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetRecordingsResponse.soap_put(soap, "trc:GetRecordingsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetRecordingsResponse.soap_put(soap, "trc:GetRecordingsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__SetRecordingConfiguration(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__SetRecordingConfiguration soap_tmp___trc__SetRecordingConfiguration;
	_trc__SetRecordingConfigurationResponse trc__SetRecordingConfigurationResponse;
	trc__SetRecordingConfigurationResponse.soap_default(soap);
	soap_default___trc__SetRecordingConfiguration(soap, &soap_tmp___trc__SetRecordingConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__SetRecordingConfiguration(soap, &soap_tmp___trc__SetRecordingConfiguration, "-trc:SetRecordingConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetRecordingConfiguration(soap_tmp___trc__SetRecordingConfiguration.trc__SetRecordingConfiguration, &trc__SetRecordingConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__SetRecordingConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__SetRecordingConfigurationResponse.soap_put(soap, "trc:SetRecordingConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__SetRecordingConfigurationResponse.soap_put(soap, "trc:SetRecordingConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetRecordingConfiguration(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetRecordingConfiguration soap_tmp___trc__GetRecordingConfiguration;
	_trc__GetRecordingConfigurationResponse trc__GetRecordingConfigurationResponse;
	trc__GetRecordingConfigurationResponse.soap_default(soap);
	soap_default___trc__GetRecordingConfiguration(soap, &soap_tmp___trc__GetRecordingConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetRecordingConfiguration(soap, &soap_tmp___trc__GetRecordingConfiguration, "-trc:GetRecordingConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetRecordingConfiguration(soap_tmp___trc__GetRecordingConfiguration.trc__GetRecordingConfiguration, &trc__GetRecordingConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetRecordingConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetRecordingConfigurationResponse.soap_put(soap, "trc:GetRecordingConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetRecordingConfigurationResponse.soap_put(soap, "trc:GetRecordingConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetRecordingOptions(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetRecordingOptions soap_tmp___trc__GetRecordingOptions;
	_trc__GetRecordingOptionsResponse trc__GetRecordingOptionsResponse;
	trc__GetRecordingOptionsResponse.soap_default(soap);
	soap_default___trc__GetRecordingOptions(soap, &soap_tmp___trc__GetRecordingOptions);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetRecordingOptions(soap, &soap_tmp___trc__GetRecordingOptions, "-trc:GetRecordingOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetRecordingOptions(soap_tmp___trc__GetRecordingOptions.trc__GetRecordingOptions, &trc__GetRecordingOptionsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetRecordingOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetRecordingOptionsResponse.soap_put(soap, "trc:GetRecordingOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetRecordingOptionsResponse.soap_put(soap, "trc:GetRecordingOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__CreateTrack(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__CreateTrack soap_tmp___trc__CreateTrack;
	_trc__CreateTrackResponse trc__CreateTrackResponse;
	trc__CreateTrackResponse.soap_default(soap);
	soap_default___trc__CreateTrack(soap, &soap_tmp___trc__CreateTrack);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__CreateTrack(soap, &soap_tmp___trc__CreateTrack, "-trc:CreateTrack", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreateTrack(soap_tmp___trc__CreateTrack.trc__CreateTrack, &trc__CreateTrackResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__CreateTrackResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__CreateTrackResponse.soap_put(soap, "trc:CreateTrackResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__CreateTrackResponse.soap_put(soap, "trc:CreateTrackResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__DeleteTrack(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__DeleteTrack soap_tmp___trc__DeleteTrack;
	_trc__DeleteTrackResponse trc__DeleteTrackResponse;
	trc__DeleteTrackResponse.soap_default(soap);
	soap_default___trc__DeleteTrack(soap, &soap_tmp___trc__DeleteTrack);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__DeleteTrack(soap, &soap_tmp___trc__DeleteTrack, "-trc:DeleteTrack", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->DeleteTrack(soap_tmp___trc__DeleteTrack.trc__DeleteTrack, &trc__DeleteTrackResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__DeleteTrackResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__DeleteTrackResponse.soap_put(soap, "trc:DeleteTrackResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__DeleteTrackResponse.soap_put(soap, "trc:DeleteTrackResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetTrackConfiguration(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetTrackConfiguration soap_tmp___trc__GetTrackConfiguration;
	_trc__GetTrackConfigurationResponse trc__GetTrackConfigurationResponse;
	trc__GetTrackConfigurationResponse.soap_default(soap);
	soap_default___trc__GetTrackConfiguration(soap, &soap_tmp___trc__GetTrackConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetTrackConfiguration(soap, &soap_tmp___trc__GetTrackConfiguration, "-trc:GetTrackConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetTrackConfiguration(soap_tmp___trc__GetTrackConfiguration.trc__GetTrackConfiguration, &trc__GetTrackConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetTrackConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetTrackConfigurationResponse.soap_put(soap, "trc:GetTrackConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetTrackConfigurationResponse.soap_put(soap, "trc:GetTrackConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__SetTrackConfiguration(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__SetTrackConfiguration soap_tmp___trc__SetTrackConfiguration;
	_trc__SetTrackConfigurationResponse trc__SetTrackConfigurationResponse;
	trc__SetTrackConfigurationResponse.soap_default(soap);
	soap_default___trc__SetTrackConfiguration(soap, &soap_tmp___trc__SetTrackConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__SetTrackConfiguration(soap, &soap_tmp___trc__SetTrackConfiguration, "-trc:SetTrackConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetTrackConfiguration(soap_tmp___trc__SetTrackConfiguration.trc__SetTrackConfiguration, &trc__SetTrackConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__SetTrackConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__SetTrackConfigurationResponse.soap_put(soap, "trc:SetTrackConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__SetTrackConfigurationResponse.soap_put(soap, "trc:SetTrackConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__CreateRecordingJob(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__CreateRecordingJob soap_tmp___trc__CreateRecordingJob;
	_trc__CreateRecordingJobResponse trc__CreateRecordingJobResponse;
	trc__CreateRecordingJobResponse.soap_default(soap);
	soap_default___trc__CreateRecordingJob(soap, &soap_tmp___trc__CreateRecordingJob);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__CreateRecordingJob(soap, &soap_tmp___trc__CreateRecordingJob, "-trc:CreateRecordingJob", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreateRecordingJob(soap_tmp___trc__CreateRecordingJob.trc__CreateRecordingJob, &trc__CreateRecordingJobResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__CreateRecordingJobResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__CreateRecordingJobResponse.soap_put(soap, "trc:CreateRecordingJobResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__CreateRecordingJobResponse.soap_put(soap, "trc:CreateRecordingJobResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__DeleteRecordingJob(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__DeleteRecordingJob soap_tmp___trc__DeleteRecordingJob;
	_trc__DeleteRecordingJobResponse trc__DeleteRecordingJobResponse;
	trc__DeleteRecordingJobResponse.soap_default(soap);
	soap_default___trc__DeleteRecordingJob(soap, &soap_tmp___trc__DeleteRecordingJob);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__DeleteRecordingJob(soap, &soap_tmp___trc__DeleteRecordingJob, "-trc:DeleteRecordingJob", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->DeleteRecordingJob(soap_tmp___trc__DeleteRecordingJob.trc__DeleteRecordingJob, &trc__DeleteRecordingJobResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__DeleteRecordingJobResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__DeleteRecordingJobResponse.soap_put(soap, "trc:DeleteRecordingJobResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__DeleteRecordingJobResponse.soap_put(soap, "trc:DeleteRecordingJobResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetRecordingJobs(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetRecordingJobs soap_tmp___trc__GetRecordingJobs;
	_trc__GetRecordingJobsResponse trc__GetRecordingJobsResponse;
	trc__GetRecordingJobsResponse.soap_default(soap);
	soap_default___trc__GetRecordingJobs(soap, &soap_tmp___trc__GetRecordingJobs);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetRecordingJobs(soap, &soap_tmp___trc__GetRecordingJobs, "-trc:GetRecordingJobs", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetRecordingJobs(soap_tmp___trc__GetRecordingJobs.trc__GetRecordingJobs, &trc__GetRecordingJobsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetRecordingJobsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetRecordingJobsResponse.soap_put(soap, "trc:GetRecordingJobsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetRecordingJobsResponse.soap_put(soap, "trc:GetRecordingJobsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__SetRecordingJobConfiguration(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__SetRecordingJobConfiguration soap_tmp___trc__SetRecordingJobConfiguration;
	_trc__SetRecordingJobConfigurationResponse trc__SetRecordingJobConfigurationResponse;
	trc__SetRecordingJobConfigurationResponse.soap_default(soap);
	soap_default___trc__SetRecordingJobConfiguration(soap, &soap_tmp___trc__SetRecordingJobConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__SetRecordingJobConfiguration(soap, &soap_tmp___trc__SetRecordingJobConfiguration, "-trc:SetRecordingJobConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetRecordingJobConfiguration(soap_tmp___trc__SetRecordingJobConfiguration.trc__SetRecordingJobConfiguration, &trc__SetRecordingJobConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__SetRecordingJobConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__SetRecordingJobConfigurationResponse.soap_put(soap, "trc:SetRecordingJobConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__SetRecordingJobConfigurationResponse.soap_put(soap, "trc:SetRecordingJobConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetRecordingJobConfiguration(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetRecordingJobConfiguration soap_tmp___trc__GetRecordingJobConfiguration;
	_trc__GetRecordingJobConfigurationResponse trc__GetRecordingJobConfigurationResponse;
	trc__GetRecordingJobConfigurationResponse.soap_default(soap);
	soap_default___trc__GetRecordingJobConfiguration(soap, &soap_tmp___trc__GetRecordingJobConfiguration);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetRecordingJobConfiguration(soap, &soap_tmp___trc__GetRecordingJobConfiguration, "-trc:GetRecordingJobConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetRecordingJobConfiguration(soap_tmp___trc__GetRecordingJobConfiguration.trc__GetRecordingJobConfiguration, &trc__GetRecordingJobConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetRecordingJobConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetRecordingJobConfigurationResponse.soap_put(soap, "trc:GetRecordingJobConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetRecordingJobConfigurationResponse.soap_put(soap, "trc:GetRecordingJobConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__SetRecordingJobMode(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__SetRecordingJobMode soap_tmp___trc__SetRecordingJobMode;
	_trc__SetRecordingJobModeResponse trc__SetRecordingJobModeResponse;
	trc__SetRecordingJobModeResponse.soap_default(soap);
	soap_default___trc__SetRecordingJobMode(soap, &soap_tmp___trc__SetRecordingJobMode);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__SetRecordingJobMode(soap, &soap_tmp___trc__SetRecordingJobMode, "-trc:SetRecordingJobMode", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetRecordingJobMode(soap_tmp___trc__SetRecordingJobMode.trc__SetRecordingJobMode, &trc__SetRecordingJobModeResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__SetRecordingJobModeResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__SetRecordingJobModeResponse.soap_put(soap, "trc:SetRecordingJobModeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__SetRecordingJobModeResponse.soap_put(soap, "trc:SetRecordingJobModeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___trc__GetRecordingJobState(RecordingBindingService *service)
{	struct soap *soap = service->soap;
	struct __trc__GetRecordingJobState soap_tmp___trc__GetRecordingJobState;
	_trc__GetRecordingJobStateResponse trc__GetRecordingJobStateResponse;
	trc__GetRecordingJobStateResponse.soap_default(soap);
	soap_default___trc__GetRecordingJobState(soap, &soap_tmp___trc__GetRecordingJobState);
	soap->encodingStyle = NULL;
	if (!soap_get___trc__GetRecordingJobState(soap, &soap_tmp___trc__GetRecordingJobState, "-trc:GetRecordingJobState", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetRecordingJobState(soap_tmp___trc__GetRecordingJobState.trc__GetRecordingJobState, &trc__GetRecordingJobStateResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	trc__GetRecordingJobStateResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || trc__GetRecordingJobStateResponse.soap_put(soap, "trc:GetRecordingJobStateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || trc__GetRecordingJobStateResponse.soap_put(soap, "trc:GetRecordingJobStateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
